import type { Metadata } from "next";
import { Sarabun } from "next/font/google";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { AbilityProvider } from "@/shared/components/providers/ability-provider";
import { AntdConfigProvider } from "@/shared/components/providers/antd-config-provider";
import ReactQueryProvider from "@/shared/components/providers/react-query-provider";
import { SessionProvider } from "@/shared/components/providers/session-provider";
import { TextScaleProvider } from "@/shared/components/text-scale";

import "./globals.css";

const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-sarabun",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={sarabun.variable}>
      <body suppressHydrationWarning>
        <NextIntlClientProvider messages={messages}>
          <SessionProvider>
            <AbilityProvider>
              <ReactQueryProvider>
                <TextScaleProvider>
                  <AntdRegistry>
                    <AntdConfigProvider>{children}</AntdConfigProvider>
                  </AntdRegistry>
                </TextScaleProvider>
              </ReactQueryProvider>
            </AbilityProvider>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
